"""
Affiliate link registry - all programs, commissions, and tracking links.
Register for these programs to get your affiliate IDs:
"""
from config import config

AFFILIATE_PROGRAMS = {
    # Copy.ai removed 2026-04-23 — partner program terminated. Was generating 4
    # clicks/14d going to a dead affiliate URL (zero attribution possible).
    "writesonic": {
        "name": "Writesonic",
        "description": "AI writing + SEO content platform with Chatsonic",
        "commission": "30% recurring",
        "commission_pct": 30,
        "cookie_days": 30,
        "avg_sale": 19,
        "category": "writing",
        "logo": "writesonic.png",
        "badge": "Best for SEO",
        "rating": 4.6,
        "reviews": 7200,
        "signup_url": f"https://writesonic.com/?via={config.AFFILIATE_IDS['writesonic']}",
        "review_keywords": ["writesonic review", "writesonic vs jasper", "writesonic pricing"],
        "monthly_est_commission": 120,
    },
    # surfer removed 2026-04-23 — PartnerStack DENIED. Impact.com route pending.
    "semrush": {
        "name": "Semrush",
        "description": "All-in-one SEO, content, and competitor research platform",
        "commission": "$200 per sale",
        "commission_pct": None,
        "commission_flat": 200,
        "cookie_days": 120,
        "avg_sale": 129,
        "category": "seo",
        "logo": "semrush.png",
        "badge": "Highest Payout",
        "rating": 4.9,
        "reviews": 22000,
        "signup_url": f"https://www.semrush.com/partner/?affcode={config.AFFILIATE_IDS['semrush']}",
        "review_keywords": ["semrush review", "semrush vs ahrefs", "semrush pricing 2026"],
        "monthly_est_commission": 400,
    },
    "pictory": {
        "name": "Pictory AI",
        "description": "Turn scripts and articles into engaging videos with AI",
        "commission": "50% first month, 20% recurring",
        "commission_pct": 20,
        "is_active": True,
        "cookie_days": 30,
        "avg_sale": 39,
        "category": "video",
        "logo": "pictory.png",
        "badge": "Best AI Video",
        "rating": 4.6,
        "reviews": 4100,
        "signup_url": f"https://pictory.ai?ref={config.AFFILIATE_IDS['pictory']}",
        "review_keywords": ["pictory ai review", "pictory ai pricing", "best ai video tools"],
        "monthly_est_commission": 150,
    },
    "invideo": {
        "name": "InVideo AI",
        "description": "Create professional videos from text prompts in minutes",
        "commission": "50% of first payment",
        "commission_pct": 50,
        "cookie_days": 60,
        "avg_sale": 25,
        "category": "video",
        "logo": "invideo.png",
        "badge": "Easiest to Use",
        "rating": 4.5,
        "reviews": 6800,
        "signup_url": f"https://invideo.io/?ref={config.AFFILIATE_IDS['invideo']}",
        "review_keywords": ["invideo ai review", "invideo pricing", "invideo vs pictory"],
        "monthly_est_commission": 100,
    },
    "murf": {
        "name": "Murf AI",
        "description": "Realistic AI voiceovers for videos, podcasts, and e-learning",
        "commission": "30% recurring",
        "commission_pct": 30,
        "is_active": True,
        "cookie_days": 30,
        "avg_sale": 29,
        "category": "audio",
        "logo": "murf.png",
        "badge": "Best Voiceover AI",
        "rating": 4.7,
        "reviews": 3200,
        "signup_url": f"https://get.murf.ai/{config.AFFILIATE_IDS['murf']}",
        "review_keywords": ["murf ai review", "murf ai pricing", "best ai voiceover tools"],
        "monthly_est_commission": 90,
    },
    "elevenlabs": {
        "name": "ElevenLabs",
        "description": "Ultra-realistic AI voice cloning and text-to-speech",
        "commission": "22% recurring",
        "commission_pct": 22,
        "is_active": True,
        "cookie_days": 30,
        "avg_sale": 22,
        "category": "audio",
        "logo": "elevenlabs.png",
        "badge": "Most Realistic Voice",
        "rating": 4.9,
        "reviews": 9800,
        "signup_url": f"https://elevenlabs.io/?from={config.AFFILIATE_IDS['elevenlabs']}",
        "review_keywords": ["elevenlabs review", "elevenlabs pricing", "elevenlabs vs murf"],
        "monthly_est_commission": 110,
    },
    # descript removed 2026-04-23 — PartnerStack DENIED.
    "fireflies": {
        "name": "Fireflies AI",
        "description": "AI meeting notetaker that records, transcribes, and summarizes calls",
        "commission": "30% recurring",
        "commission_pct": 30,
        "is_active": True,
        "cookie_days": 30,
        "avg_sale": 18,
        "category": "productivity",
        "logo": "fireflies.png",
        "badge": "Best Meeting AI",
        "rating": 4.6,
        "reviews": 4400,
        "signup_url": f"https://fireflies.ai/?fpr={config.AFFILIATE_IDS['fireflies']}",
        "review_keywords": ["fireflies ai review", "fireflies ai pricing", "best meeting ai tools"],
        "monthly_est_commission": 95,
    },
    "speechify": {
        "name": "Speechify",
        "description": "Turn any text into natural-sounding audio — read 4.5x faster",
        "commission": "50% per sale",
        "commission_pct": 50,
        "cookie_days": 90,
        "avg_sale": 139,
        "category": "audio",
        "logo": "speechify.png",
        "badge": "50% Commission",
        "rating": 4.8,
        "reviews": 18000,
        "signup_url": f"https://speechify.com/affiliate/?ref={config.AFFILIATE_IDS['speechify']}",
        "review_keywords": ["speechify review", "speechify pricing", "speechify vs natural reader"],
        "monthly_est_commission": 280,
    },
    # getresponse removed 2026-04-23 — PartnerStack DENIED.
    "hubspot": {
        "name": "HubSpot",
        "description": "AI-powered CRM, marketing, sales, and customer service platform",
        "commission": "30% recurring for 12 months",
        "commission_pct": 30,
        "cookie_days": 90,
        "avg_sale": 50,
        "category": "productivity",
        "logo": "hubspot.png",
        "badge": "Top CRM",
        "rating": 4.9,
        "reviews": 35000,
        "signup_url": f"https://www.hubspot.com/?hubs_signup-url=affiliate&hubs_signup-cta={config.AFFILIATE_IDS['hubspot']}",
        "review_keywords": ["hubspot review", "hubspot pricing", "hubspot vs salesforce"],
        "monthly_est_commission": 300,
    },
    # quillbot / kit / webflow removed 2026-04-23 — PartnerStack DENIED.
    "grammarly": {
        "name": "Grammarly",
        "description": "AI writing assistant for grammar, clarity, and tone — used by 30M+ people",
        "commission": "$0.20 per free signup, $20 per premium upgrade",
        "commission_pct": None,
        "commission_flat": 20,
        "cookie_days": 90,
        "avg_sale": 12,
        "category": "writing",
        "logo": "grammarly.png",
        "badge": "30M+ Users",
        "signup_url": f"https://www.grammarly.com/referrals/{config.AFFILIATE_IDS.get('grammarly', '')}",
        "review_keywords": ["grammarly review", "grammarly vs quillbot", "best grammar checker ai"],
        "monthly_est_commission": 140,
        "apply_url": "https://www.grammarly.com/affiliates",
        "network": "Impact.com",
    },
    "synthesia": {
        "name": "Synthesia",
        "description": "Create AI videos with digital avatars — no camera or filming needed",
        "commission": "20% recurring",
        "commission_pct": 20,
        "cookie_days": 60,
        "avg_sale": 29,
        "category": "video",
        "logo": "synthesia.png",
        "badge": "Best AI Avatar Video",
        "signup_url": f"https://www.synthesia.io/?via={config.AFFILIATE_IDS.get('synthesia', '')}",
        "review_keywords": ["synthesia review", "synthesia pricing", "synthesia vs pictory", "ai avatar video"],
        "monthly_est_commission": 95,
        "apply_url": "https://www.synthesia.io/affiliates",
        "network": "Direct",
    },
    # runway removed 2026-04-23 — no public affiliate program exists.
    # ── NEW PROGRAMS (April 2026 expansion) ──────────────────────────────────
    "notion": {
        "name": "Notion",
        "description": "All-in-one workspace with AI writing, project management, and wikis",
        "commission": "50% recurring for 12 months",
        "commission_pct": 50,
        "cookie_days": 180,
        "avg_sale": 10,
        "category": "productivity",
        "logo": "notion.png",
        "badge": "Top Pick",
        "rating": 4.8,
        "reviews": 15000,
        "signup_url": f"https://www.notion.so/?r={config.AFFILIATE_IDS.get('notion', '')}",
        "review_keywords": ["notion review", "notion ai review", "notion pricing", "notion vs clickup"],
        "monthly_est_commission": 250,
        "apply_url": "https://www.notion.com/affiliates",
        "network": "Direct",
    },
    "scalenut": {
        "name": "Scalenut",
        "description": "AI-powered SEO content platform with keyword planning and SERP analysis",
        "commission": "40-60% tiered recurring",
        "commission_pct": 40,
        "cookie_days": 60,
        "avg_sale": 39,
        "category": "seo",
        "logo": "scalenut.png",
        "badge": "",
        "rating": 4.5,
        "reviews": 2100,
        "signup_url": f"https://www.scalenut.com/?fpr={config.AFFILIATE_IDS.get('scalenut', '')}",
        "review_keywords": ["scalenut review", "scalenut pricing", "scalenut vs surfer seo"],
        "monthly_est_commission": 160,
        "apply_url": "https://www.scalenut.com/affiliate",
        "network": "FirstPromoter",
    },
    "anyword": {
        "name": "Anyword",
        "description": "AI copywriting platform with performance prediction scoring",
        "commission": "40-45% recurring",
        "commission_pct": 40,
        "cookie_days": 90,
        "avg_sale": 39,
        "category": "writing",
        "logo": "anyword.png",
        "badge": "",
        "rating": 4.6,
        "reviews": 1800,
        "signup_url": f"https://anyword.com/?via={config.AFFILIATE_IDS.get('anyword', '')}",
        "review_keywords": ["anyword review", "anyword pricing", "anyword vs jasper"],
        "monthly_est_commission": 140,
        "apply_url": "https://anyword.com/affiliates/",
        "network": "Direct",
    },
    "seranking": {
        "name": "SE Ranking",
        "description": "All-in-one SEO platform with rank tracker, site audit, and competitor analysis",
        "commission": "30% lifetime recurring",
        "commission_pct": 30,
        "cookie_days": 120,
        "avg_sale": 55,
        "category": "seo",
        "logo": "seranking.png",
        "badge": "",
        "rating": 4.6,
        "reviews": 3200,
        "signup_url": f"https://seranking.com/?ga={config.AFFILIATE_IDS.get('seranking', '')}",
        "review_keywords": ["se ranking review", "se ranking pricing", "se ranking vs semrush"],
        "monthly_est_commission": 165,
        "apply_url": "https://seranking.com/affiliate.html",
        "network": "Direct",
    },
    "make": {
        "name": "Make.com",
        "description": "Visual automation platform connecting 1500+ apps with AI workflows",
        "commission": "35% recurring for 12 months",
        "commission_pct": 35,
        "cookie_days": 60,
        "avg_sale": 16,
        "category": "productivity",
        "logo": "make.png",
        "badge": "",
        "rating": 4.7,
        "reviews": 4500,
        "signup_url": f"https://www.make.com/en/register?pc={config.AFFILIATE_IDS.get('make', '')}",
        "review_keywords": ["make.com review", "make vs zapier", "make automation review"],
        "monthly_est_commission": 110,
        "apply_url": "https://www.make.com/en/partners",
        "network": "Direct",
    },
    "fliki": {
        "name": "Fliki",
        "description": "AI video creation with text-to-video, voiceover, and avatar support",
        "commission": "30% lifetime recurring + bonuses",
        "commission_pct": 30,
        "cookie_days": 30,
        "avg_sale": 28,
        "category": "video",
        "logo": "fliki.png",
        "badge": "",
        "rating": 4.5,
        "reviews": 2800,
        "signup_url": f"https://fliki.ai/?via={config.AFFILIATE_IDS.get('fliki', '')}",
        "review_keywords": ["fliki review", "fliki pricing", "fliki vs synthesia"],
        "monthly_est_commission": 120,
        "apply_url": "https://affiliates.fliki.ai/signup",
        "network": "Direct",
    },
    "rytr": {
        "name": "Rytr",
        "description": "Budget-friendly AI writing assistant with 40+ use cases",
        "commission": "30% lifetime recurring",
        "commission_pct": 30,
        "cookie_days": 60,
        "avg_sale": 9,
        "category": "writing",
        "logo": "rytr.png",
        "badge": "",
        "rating": 4.4,
        "reviews": 5600,
        "signup_url": f"https://rytr.me/?via={config.AFFILIATE_IDS.get('rytr', '')}",
        "review_keywords": ["rytr review", "rytr pricing", "rytr vs copy ai"],
        "monthly_est_commission": 80,
        "apply_url": "https://affiliates.rytr.me/signup",
        "network": "FirstPromoter",
    },
    "koala": {
        "name": "Koala AI",
        "description": "AI SEO writer that produces long-form, Google-ready articles in one click",
        "commission": "30% lifetime recurring",
        "commission_pct": 30,
        "cookie_days": 60,
        "avg_sale": 25,
        "category": "writing",
        "logo": "koala.png",
        "badge": "",
        "rating": 4.5,
        "reviews": 1200,
        "signup_url": f"https://koala.sh/?via={config.AFFILIATE_IDS.get('koala', '')}",
        "review_keywords": ["koala ai review", "koala writer review", "koala vs jasper"],
        "monthly_est_commission": 100,
        "apply_url": "https://friends.koala.sh/signup",
        "network": "Direct",
    },
    "frase": {
        "name": "Frase.io",
        "description": "AI SEO content optimization and brief generation tool",
        "commission": "30% recurring for 12 months",
        "commission_pct": 30,
        "cookie_days": 60,
        "avg_sale": 45,
        "category": "seo",
        "logo": "frase.png",
        "badge": "",
        "rating": 4.5,
        "reviews": 2400,
        "signup_url": f"https://www.frase.io/?via={config.AFFILIATE_IDS.get('frase', '')}",
        "review_keywords": ["frase review", "frase pricing", "frase vs surfer"],
        "monthly_est_commission": 135,
        "apply_url": "https://affiliates.frase.io/",
        "network": "FirstPromoter",
    },
    "hostinger": {
        "name": "Hostinger",
        "description": "Web hosting with AI website builder, domain, and SSL included",
        "commission": "40-60% per sale",
        "commission_pct": 40,
        "cookie_days": 30,
        "avg_sale": 48,
        "category": "productivity",
        "logo": "hostinger.png",
        "badge": "",
        "rating": 4.6,
        "reviews": 22000,
        "signup_url": f"https://www.hostinger.com/?REFERRALCODE={config.AFFILIATE_IDS.get('hostinger', '')}",
        "review_keywords": ["hostinger review", "hostinger ai builder", "hostinger pricing"],
        "monthly_est_commission": 200,
        "apply_url": "https://www.hostinger.com/affiliates",
        "network": "Direct",
    },
    "heygen": {
        "name": "HeyGen",
        "description": "AI video creation with realistic talking avatars and voice cloning",
        "commission": "35% recurring for 3 months",
        "commission_pct": 35,
        "cookie_days": 30,
        "avg_sale": 29,
        "category": "video",
        "logo": "heygen.png",
        "badge": "",
        "rating": 4.6,
        "reviews": 3100,
        "signup_url": f"https://www.heygen.com/?sid={config.AFFILIATE_IDS.get('heygen', '')}",
        "review_keywords": ["heygen review", "heygen pricing", "heygen vs synthesia"],
        "monthly_est_commission": 100,
        "apply_url": "https://www.heygen.com/affiliate-program",
        "network": "Direct",
    },
    "playht": {
        "name": "Play.ht",
        "description": "Ultra-realistic AI text-to-speech with voice cloning and API",
        "commission": "25% recurring",
        "commission_pct": 25,
        "cookie_days": 60,
        "avg_sale": 31,
        "category": "audio",
        "logo": "playht.png",
        "badge": "",
        "rating": 4.4,
        "reviews": 1800,
        "signup_url": f"https://play.ht/?via={config.AFFILIATE_IDS.get('playht', '')}",
        "review_keywords": ["play.ht review", "play ht pricing", "play ht vs elevenlabs"],
        "monthly_est_commission": 80,
        "apply_url": "https://play.ht/affiliates/",
        "network": "Rewardful",
    },
    "mangools": {
        "name": "Mangools",
        "description": "Beginner-friendly SEO toolset with KWFinder, SERPChecker, and more",
        "commission": "Up to 35% lifetime recurring",
        "commission_pct": 35,
        "cookie_days": 30,
        "avg_sale": 30,
        "category": "seo",
        "logo": "mangools.png",
        "badge": "",
        "rating": 4.5,
        "reviews": 3800,
        "signup_url": f"https://mangools.com/?a={config.AFFILIATE_IDS.get('mangools', '')}",
        "review_keywords": ["mangools review", "kwfinder review", "mangools vs ahrefs"],
        "monthly_est_commission": 105,
        "apply_url": "https://mangools.com/affiliate-program",
        "network": "Direct",
    },
    "fotor": {
        "name": "Fotor",
        "description": "AI photo editor and graphic design tool with templates and effects",
        "commission": "35% first + 25% renewals for 1 year",
        "commission_pct": 35,
        "cookie_days": 45,
        "avg_sale": 40,
        "category": "productivity",
        "logo": "fotor.png",
        "badge": "",
        "rating": 4.3,
        "reviews": 4200,
        "signup_url": f"https://www.fotor.com/?ref={config.AFFILIATE_IDS.get('fotor', '')}",
        "review_keywords": ["fotor review", "fotor ai", "fotor vs canva"],
        "monthly_est_commission": 90,
        "apply_url": "https://www.fotor.com/affiliates.html",
        "network": "Direct",
    },
}

CATEGORIES = {
    "writing": {"label": "AI Writing Tools", "icon": "✍️", "description": "AI-powered writing assistants"},
    "seo": {"label": "AI SEO Tools", "icon": "🔍", "description": "SEO and content optimization"},
    "video": {"label": "AI Video Tools", "icon": "🎬", "description": "Create and edit videos with AI"},
    "audio": {"label": "AI Voice Tools", "icon": "🎙️", "description": "Voice cloning and text-to-speech"},
    "productivity": {"label": "AI Productivity", "icon": "⚡", "description": "Work smarter with AI"},
}

def get_tools_by_category(category: str = None):
    if category:
        return {k: v for k, v in AFFILIATE_PROGRAMS.items() if v["category"] == category}
    return AFFILIATE_PROGRAMS

def get_affiliate_link(tool_key: str) -> str:
    tool = AFFILIATE_PROGRAMS.get(tool_key)
    if not tool:
        return "#"
    return tool["signup_url"]

def get_monthly_revenue_estimate() -> dict:
    total = 0
    breakdown = {}
    for key, tool in AFFILIATE_PROGRAMS.items():
        est = tool.get("monthly_est_commission", 0)
        breakdown[tool["name"]] = est
        total += est
    return {"total_monthly": total, "total_weekly": total / 4.33, "breakdown": breakdown}


# ── Programs NOT yet active — apply and move to AFFILIATE_PROGRAMS once approved ──
PENDING_PROGRAMS = {
    "jasper": {
        "name": "Jasper AI",
        "description": "AI writing assistant for marketers and content teams",
        "apply_url": "https://www.jasper.ai/affiliates",
        "network": "Direct",
        "commission": "30% recurring monthly",
    },
    "canva": {
        "name": "Canva",
        "description": "AI-powered design platform",
        "apply_url": "https://www.canva.com/affiliates/",
        "network": "Impact.com",
        "commission": "Up to $36 per Canva Pro sale",
    },
}
