"""
Affiliate link registry - all programs, commissions, and tracking links.
Register for these programs to get your affiliate IDs:
"""
from config import config

AFFILIATE_PROGRAMS = {
    "copyai": {
        "name": "Copy.ai",
        "description": "AI-powered copywriting for blogs, ads, and social media",
        "commission": "45% recurring",
        "commission_pct": 45,
        "cookie_days": 60,
        "avg_sale": 36,
        "category": "writing",
        "logo": "copyai.png",
        "badge": "Best Value",
        "rating": 4.7,
        "reviews": 8900,
        "signup_url": f"https://www.copy.ai/?via={config.AFFILIATE_IDS['copyai']}",
        "review_keywords": ["copy ai review", "copy.ai pricing", "copy ai vs jasper"],
        "monthly_est_commission": 180,
    },
    "writesonic": {
        "name": "Writesonic",
        "description": "AI writing + SEO content platform with Chatsonic",
        "commission": "30% recurring",
        "commission_pct": 30,
        "cookie_days": 30,
        "avg_sale": 19,
        "category": "writing",
        "logo": "writesonic.png",
        "badge": "Best for SEO",
        "rating": 4.6,
        "reviews": 7200,
        "signup_url": f"https://writesonic.com/?via={config.AFFILIATE_IDS['writesonic']}",
        "review_keywords": ["writesonic review", "writesonic vs jasper", "writesonic pricing"],
        "monthly_est_commission": 120,
    },
    "surfer": {
        "name": "Surfer SEO",
        "description": "AI-powered SEO content optimization tool",
        "commission": "25% recurring",
        "commission_pct": 25,
        "cookie_days": 60,
        "avg_sale": 89,
        "category": "seo",
        "logo": "surfer.png",
        "badge": "Best SEO Tool",
        "rating": 4.8,
        "reviews": 5300,
        "signup_url": f"https://surferseo.com/?via={config.AFFILIATE_IDS['surfer']}",
        "review_keywords": ["surfer seo review", "surfer seo pricing", "best seo ai tools"],
        "monthly_est_commission": 220,
    },
    "semrush": {
        "name": "Semrush",
        "description": "All-in-one SEO, content, and competitor research platform",
        "commission": "$200 per sale",
        "commission_pct": None,
        "commission_flat": 200,
        "cookie_days": 120,
        "avg_sale": 129,
        "category": "seo",
        "logo": "semrush.png",
        "badge": "Highest Payout",
        "rating": 4.9,
        "reviews": 22000,
        "signup_url": f"https://www.semrush.com/partner/?affcode={config.AFFILIATE_IDS['semrush']}",
        "review_keywords": ["semrush review", "semrush vs ahrefs", "semrush pricing 2026"],
        "monthly_est_commission": 400,
    },
    "pictory": {
        "name": "Pictory AI",
        "description": "Turn scripts and articles into engaging videos with AI",
        "commission": "50% first month, 20% recurring",
        "commission_pct": 20,
        "cookie_days": 30,
        "avg_sale": 39,
        "category": "video",
        "logo": "pictory.png",
        "badge": "Best AI Video",
        "rating": 4.6,
        "reviews": 4100,
        "signup_url": f"https://pictory.ai?ref={config.AFFILIATE_IDS['pictory']}",
        "review_keywords": ["pictory ai review", "pictory ai pricing", "best ai video tools"],
        "monthly_est_commission": 150,
    },
    "invideo": {
        "name": "InVideo AI",
        "description": "Create professional videos from text prompts in minutes",
        "commission": "50% of first payment",
        "commission_pct": 50,
        "cookie_days": 60,
        "avg_sale": 25,
        "category": "video",
        "logo": "invideo.png",
        "badge": "Easiest to Use",
        "rating": 4.5,
        "reviews": 6800,
        "signup_url": f"https://invideo.io/?ref={config.AFFILIATE_IDS['invideo']}",
        "review_keywords": ["invideo ai review", "invideo pricing", "invideo vs pictory"],
        "monthly_est_commission": 100,
    },
    "murf": {
        "name": "Murf AI",
        "description": "Realistic AI voiceovers for videos, podcasts, and e-learning",
        "commission": "30% recurring",
        "commission_pct": 30,
        "cookie_days": 30,
        "avg_sale": 29,
        "category": "audio",
        "logo": "murf.png",
        "badge": "Best Voiceover AI",
        "rating": 4.7,
        "reviews": 3200,
        "signup_url": f"https://murf.ai/?ref={config.AFFILIATE_IDS['murf']}",
        "review_keywords": ["murf ai review", "murf ai pricing", "best ai voiceover tools"],
        "monthly_est_commission": 90,
    },
    "elevenlabs": {
        "name": "ElevenLabs",
        "description": "Ultra-realistic AI voice cloning and text-to-speech",
        "commission": "22% recurring",
        "commission_pct": 22,
        "cookie_days": 30,
        "avg_sale": 22,
        "category": "audio",
        "logo": "elevenlabs.png",
        "badge": "Most Realistic Voice",
        "rating": 4.9,
        "reviews": 9800,
        "signup_url": f"https://elevenlabs.io/?from={config.AFFILIATE_IDS['elevenlabs']}",
        "review_keywords": ["elevenlabs review", "elevenlabs pricing", "elevenlabs vs murf"],
        "monthly_est_commission": 110,
    },
    "descript": {
        "name": "Descript",
        "description": "AI video and podcast editing — edit media like a Word doc",
        "commission": "15% recurring",
        "commission_pct": 15,
        "cookie_days": 30,
        "avg_sale": 24,
        "category": "video",
        "logo": "descript.png",
        "badge": "Best for Creators",
        "rating": 4.7,
        "reviews": 5600,
        "signup_url": f"https://www.descript.com/affiliates?ref={config.AFFILIATE_IDS['descript']}",
        "review_keywords": ["descript review", "descript pricing", "descript vs premiere"],
        "monthly_est_commission": 80,
    },
    "fireflies": {
        "name": "Fireflies AI",
        "description": "AI meeting notetaker that records, transcribes, and summarizes calls",
        "commission": "30% recurring",
        "commission_pct": 30,
        "cookie_days": 30,
        "avg_sale": 18,
        "category": "productivity",
        "logo": "fireflies.png",
        "badge": "Best Meeting AI",
        "rating": 4.6,
        "reviews": 4400,
        "signup_url": f"https://fireflies.ai/?fpr={config.AFFILIATE_IDS['fireflies']}",
        "review_keywords": ["fireflies ai review", "fireflies ai pricing", "best meeting ai tools"],
        "monthly_est_commission": 95,
    },
    "speechify": {
        "name": "Speechify",
        "description": "Turn any text into natural-sounding audio — read 4.5x faster",
        "commission": "50% per sale",
        "commission_pct": 50,
        "cookie_days": 90,
        "avg_sale": 139,
        "category": "audio",
        "logo": "speechify.png",
        "badge": "50% Commission",
        "rating": 4.8,
        "reviews": 18000,
        "signup_url": f"https://speechify.com/affiliate/?ref={config.AFFILIATE_IDS['speechify']}",
        "review_keywords": ["speechify review", "speechify pricing", "speechify vs natural reader"],
        "monthly_est_commission": 280,
    },
    "getresponse": {
        "name": "GetResponse",
        "description": "AI-powered email marketing, automation, and landing pages",
        "commission": "40% recurring for 12 months",
        "commission_pct": 40,
        "cookie_days": 120,
        "avg_sale": 49,
        "category": "productivity",
        "logo": "getresponse.png",
        "badge": "40% Recurring",
        "rating": 4.7,
        "reviews": 11200,
        "signup_url": f"https://www.getresponse.com/?a={config.AFFILIATE_IDS['getresponse']}",
        "review_keywords": ["getresponse review", "getresponse pricing", "getresponse vs mailchimp"],
        "monthly_est_commission": 240,
    },
    "hubspot": {
        "name": "HubSpot",
        "description": "AI-powered CRM, marketing, sales, and customer service platform",
        "commission": "30% recurring for 12 months",
        "commission_pct": 30,
        "cookie_days": 90,
        "avg_sale": 50,
        "category": "productivity",
        "logo": "hubspot.png",
        "badge": "Top CRM",
        "rating": 4.9,
        "reviews": 35000,
        "signup_url": f"https://www.hubspot.com/?hubs_signup-url=affiliate&hubs_signup-cta={config.AFFILIATE_IDS['hubspot']}",
        "review_keywords": ["hubspot review", "hubspot pricing", "hubspot vs salesforce"],
        "monthly_est_commission": 300,
    },
    "quillbot": {
        "name": "QuillBot",
        "description": "AI paraphrasing, grammar checking, and writing enhancement tool",
        "commission": "20% recurring annual",
        "commission_pct": 20,
        "cookie_days": 90,
        "avg_sale": 99,
        "category": "writing",
        "logo": "quillbot.png",
        "badge": "Best Paraphraser",
        "rating": 4.7,
        "reviews": 15000,
        "signup_url": f"https://quillbot.com/?ref={config.AFFILIATE_IDS.get('quillbot', '')}",
        "review_keywords": ["quillbot review", "quillbot pricing", "quillbot vs grammarly"],
        "monthly_est_commission": 160,
    },
    "kit": {
        "name": "Kit (ConvertKit)",
        "description": "Email marketing platform built for creators — newsletters, automations, landing pages",
        "commission": "50% recurring for 24 months",
        "commission_pct": 50,
        "cookie_days": 90,
        "avg_sale": 29,
        "category": "productivity",
        "logo": "kit.png",
        "badge": "50% For 2 Years",
        "rating": 4.8,
        "reviews": 9000,
        "signup_url": f"https://kit.com/?ref={config.AFFILIATE_IDS.get('kit', '')}",
        "review_keywords": ["convertkit review", "kit email marketing", "best email platform creators"],
        "monthly_est_commission": 190,
    },
    "webflow": {
        "name": "Webflow",
        "description": "No-code website builder with CMS and hosting — build without developers",
        "commission": "50% recurring for 12 months",
        "commission_pct": 50,
        "cookie_days": 90,
        "avg_sale": 29,
        "category": "productivity",
        "logo": "webflow.png",
        "badge": "50% Commission",
        "rating": 4.8,
        "reviews": 12000,
        "signup_url": f"https://webflow.com/r/{config.AFFILIATE_IDS.get('webflow', '')}",
        "review_keywords": ["webflow review", "webflow pricing", "webflow vs wordpress"],
        "monthly_est_commission": 180,
    },
    "grammarly": {
        "name": "Grammarly",
        "description": "AI writing assistant for grammar, clarity, and tone — used by 30M+ people",
        "commission": "$0.20 per free signup, $20 per premium upgrade",
        "commission_pct": None,
        "commission_flat": 20,
        "cookie_days": 90,
        "avg_sale": 12,
        "category": "writing",
        "logo": "grammarly.png",
        "badge": "30M+ Users",
        "signup_url": f"https://www.grammarly.com/referrals/{config.AFFILIATE_IDS.get('grammarly', '')}",
        "review_keywords": ["grammarly review", "grammarly vs quillbot", "best grammar checker ai"],
        "monthly_est_commission": 140,
        "apply_url": "https://www.grammarly.com/affiliates",
        "network": "Impact.com",
    },
    "synthesia": {
        "name": "Synthesia",
        "description": "Create AI videos with digital avatars — no camera or filming needed",
        "commission": "20% recurring",
        "commission_pct": 20,
        "cookie_days": 60,
        "avg_sale": 29,
        "category": "video",
        "logo": "synthesia.png",
        "badge": "Best AI Avatar Video",
        "signup_url": f"https://www.synthesia.io/?via={config.AFFILIATE_IDS.get('synthesia', '')}",
        "review_keywords": ["synthesia review", "synthesia pricing", "synthesia vs pictory", "ai avatar video"],
        "monthly_est_commission": 95,
        "apply_url": "https://www.synthesia.io/affiliates",
        "network": "Direct",
    },
    "runway": {
        "name": "Runway ML",
        "description": "AI video generation and editing — Gen-2 video creation from text or images",
        "commission": "20% recurring",
        "commission_pct": 20,
        "cookie_days": 30,
        "avg_sale": 15,
        "category": "video",
        "logo": "runway.png",
        "badge": "Best AI Video Gen",
        "signup_url": f"https://runwayml.com/?ref={config.AFFILIATE_IDS.get('runway', '')}",
        "review_keywords": ["runway ml review", "runway ai pricing", "runway vs pika labs", "ai video generation"],
        "monthly_est_commission": 75,
        "apply_url": "https://runwayml.com/affiliates",
        "network": "Direct",
    },
}

CATEGORIES = {
    "writing": {"label": "AI Writing Tools", "icon": "✍️", "description": "AI-powered writing assistants"},
    "seo": {"label": "AI SEO Tools", "icon": "🔍", "description": "SEO and content optimization"},
    "video": {"label": "AI Video Tools", "icon": "🎬", "description": "Create and edit videos with AI"},
    "audio": {"label": "AI Voice Tools", "icon": "🎙️", "description": "Voice cloning and text-to-speech"},
    "productivity": {"label": "AI Productivity", "icon": "⚡", "description": "Work smarter with AI"},
}

def get_tools_by_category(category: str = None):
    if category:
        return {k: v for k, v in AFFILIATE_PROGRAMS.items() if v["category"] == category}
    return AFFILIATE_PROGRAMS

def get_affiliate_link(tool_key: str) -> str:
    tool = AFFILIATE_PROGRAMS.get(tool_key)
    if not tool:
        return "#"
    return tool["signup_url"]

def get_monthly_revenue_estimate() -> dict:
    total = 0
    breakdown = {}
    for key, tool in AFFILIATE_PROGRAMS.items():
        est = tool.get("monthly_est_commission", 0)
        breakdown[tool["name"]] = est
        total += est
    return {"total_monthly": total, "total_weekly": total / 4.33, "breakdown": breakdown}


# ── Programs NOT yet active — apply and move to AFFILIATE_PROGRAMS once approved ──
PENDING_PROGRAMS = {
    "jasper": {
        "name": "Jasper AI",
        "description": "AI writing assistant for marketers and content teams",
        "apply_url": "https://www.jasper.ai/affiliates",
        "network": "Direct",
        "commission": "30% recurring monthly",
    },
    "canva": {
        "name": "Canva",
        "description": "AI-powered design platform",
        "apply_url": "https://www.canva.com/affiliates/",
        "network": "Impact.com",
        "commission": "Up to $36 per Canva Pro sale",
    },
}
