"""
Automated email system:
- Welcome sequence for new subscribers
- Weekly newsletter (auto-generated by AI, sent every Monday)
- Click tracking via affiliate links
"""
import resend
import logging
from datetime import datetime
from config import config
from database.db import (
    get_subscribers, get_articles, mark_welcome_sent, add_subscriber,
    get_subscriber_count
)
from affiliate.links import AFFILIATE_PROGRAMS

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

resend.api_key = config.RESEND_API_KEY

WELCOME_EMAIL_HTML = """
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; margin: 0; padding: 20px; }}
  .container {{ max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.07); }}
  .header {{ background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); padding: 40px 32px; text-align: center; }}
  .header h1 {{ color: white; margin: 0; font-size: 28px; font-weight: 700; }}
  .header p {{ color: rgba(255,255,255,0.85); margin: 8px 0 0; font-size: 16px; }}
  .body {{ padding: 32px; }}
  .body h2 {{ color: #1e293b; font-size: 22px; margin-top: 0; }}
  .body p {{ color: #475569; line-height: 1.6; }}
  .tool-card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 12px 0; }}
  .tool-card h3 {{ margin: 0 0 4px; color: #1e293b; font-size: 16px; }}
  .tool-card p {{ margin: 0 0 10px; color: #64748b; font-size: 14px; }}
  .tool-card a {{ background: #6366f1; color: white; padding: 8px 16px; border-radius: 6px; text-decoration: none; font-size: 14px; font-weight: 600; }}
  .cta-box {{ background: linear-gradient(135deg, #f0f9ff, #e0f2fe); border: 1px solid #bae6fd; border-radius: 10px; padding: 24px; text-align: center; margin: 24px 0; }}
  .cta-box h3 {{ color: #0369a1; margin: 0 0 8px; }}
  .cta-box p {{ color: #0c4a6e; margin: 0 0 16px; font-size: 14px; }}
  .footer {{ background: #f8fafc; padding: 20px 32px; text-align: center; border-top: 1px solid #e2e8f0; }}
  .footer p {{ color: #94a3b8; font-size: 12px; margin: 4px 0; }}
  .footer a {{ color: #6366f1; text-decoration: none; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>🤖 Welcome to {site_name}!</h1>
    <p>Your weekly guide to the best AI tools</p>
  </div>
  <div class="body">
    <h2>Hey {name}, you're in! 🎉</h2>
    <p>Thanks for subscribing to <strong>{site_name}</strong>. Every week, I'll send you:</p>
    <ul style="color:#475569;line-height:1.8">
      <li>🔥 In-depth reviews of the hottest AI tools</li>
      <li>📊 Head-to-head comparisons so you pick the right tool</li>
      <li>💰 Exclusive deals and discounts (saved me $200+ last year)</li>
      <li>⚡ Tips to automate your work with AI</li>
    </ul>
    <p>To get you started, here are the <strong>3 AI tools I recommend most right now:</strong></p>

    <div class="tool-card">
      <h3>✍️ Jasper AI — Best AI Writing Tool</h3>
      <p>Used by 100,000+ marketers. 30% recurring commission for referrals.</p>
      <a href="{jasper_url}" target="_blank">Try Jasper Free →</a>
    </div>

    <div class="tool-card">
      <h3>🔍 Surfer SEO — Best AI SEO Tool</h3>
      <p>Ranks content faster by optimizing in real-time. Trusted by 17,000+ agencies.</p>
      <a href="{surfer_url}" target="_blank">Try Surfer SEO →</a>
    </div>

    <div class="tool-card">
      <h3>🎬 Pictory AI — Best AI Video Tool</h3>
      <p>Turn your blog posts into viral videos in minutes. No filming needed.</p>
      <a href="{pictory_url}" target="_blank">Try Pictory Free →</a>
    </div>

    <div class="cta-box">
      <h3>📚 Start Reading</h3>
      <p>Check out our most popular guide to get started:</p>
      <a href="{site_url}/articles/10-best-ai-writing-tools-in-2026" style="background:#0369a1;color:white;padding:10px 20px;border-radius:6px;text-decoration:none;font-weight:600">10 Best AI Writing Tools →</a>
    </div>

    <p>See you in your inbox next Monday! 🚀</p>
    <p style="color:#64748b;font-size:14px">— The {site_name} Team</p>
  </div>
  <div class="footer">
    <p>You subscribed at <a href="{site_url}">{site_url}</a></p>
    <p><a href="{site_url}/unsubscribe?email={{{{email}}}}">Unsubscribe</a> · <a href="{site_url}/privacy">Privacy Policy</a></p>
  </div>
</div>
</body>
</html>
"""

def send_welcome_email(subscriber_email: str, subscriber_name: str = "there"):
    """Send welcome email to new subscriber."""
    html = WELCOME_EMAIL_HTML.format(
        site_name=config.SITE_NAME,
        site_url=config.SITE_URL,
        name=subscriber_name if subscriber_name else "there",
        jasper_url=AFFILIATE_PROGRAMS["jasper"]["signup_url"],
        surfer_url=AFFILIATE_PROGRAMS["surfer"]["signup_url"],
        pictory_url=AFFILIATE_PROGRAMS["pictory"]["signup_url"],
    )

    try:
        response = resend.Emails.send({
            "from": f"{config.FROM_NAME} <{config.FROM_EMAIL}>",
            "to": [subscriber_email],
            "subject": f"Welcome to {config.SITE_NAME} 🤖 Your AI tools guide starts here",
            "html": html,
        })
        mark_welcome_sent(subscriber_email)
        log.info(f"Welcome email sent to {subscriber_email}")
        return True
    except Exception as e:
        log.error(f"Failed to send welcome email to {subscriber_email}: {e}")
        return False

def send_welcome_to_pending():
    """Send welcome emails to any subscribers who haven't received one yet."""
    from database.db import get_conn
    conn = get_conn()
    pending = conn.execute("""
        SELECT email, name FROM subscribers WHERE welcome_sent=0 AND status='active'
    """).fetchall()
    conn.close()

    sent = 0
    for sub in pending:
        if send_welcome_email(sub["email"], sub["name"]):
            sent += 1
    log.info(f"Welcome emails sent: {sent}")
    return sent

def generate_newsletter_html(articles: list, week_num: int) -> str:
    """Build the weekly newsletter HTML from recent articles."""
    article_blocks = ""
    for i, article in enumerate(articles[:5]):
        tool_key = article.get("featured_tool", "")
        cta = ""
        if tool_key and tool_key in AFFILIATE_PROGRAMS:
            t = AFFILIATE_PROGRAMS[tool_key]
            cta = f'<p><a href="{t["signup_url"]}" style="background:#6366f1;color:white;padding:8px 16px;border-radius:6px;text-decoration:none;font-size:13px;font-weight:600">Try {t["name"]} Free →</a></p>'

        article_blocks += f"""
        <div style="border-bottom:1px solid #e2e8f0;padding:20px 0;">
          <h3 style="margin:0 0 8px;font-size:18px;">
            <a href="{config.SITE_URL}/articles/{article['slug']}" style="color:#1e293b;text-decoration:none;">
              {article['title']}
            </a>
          </h3>
          <p style="color:#64748b;margin:0 0 12px;line-height:1.6;font-size:14px;">{article.get('meta_description','')}</p>
          <a href="{config.SITE_URL}/articles/{article['slug']}" style="color:#6366f1;font-size:13px;font-weight:600;text-decoration:none;">Read Full Article →</a>
          {cta}
        </div>
        """

    # Pick top tools to feature
    featured = ["semrush", "jasper", "elevenlabs"]
    deals_blocks = ""
    for fk in featured:
        if fk in AFFILIATE_PROGRAMS:
            t = AFFILIATE_PROGRAMS[fk]
            deals_blocks += f"""
            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px;margin:10px 0;display:flex;justify-content:space-between;align-items:center;">
              <div>
                <strong style="color:#1e293b;font-size:15px;">{t['name']}</strong><br>
                <span style="color:#64748b;font-size:13px;">{t['commission']} commission · {t['cookie_days']}-day cookie</span>
              </div>
              <a href="{t['signup_url']}" style="background:#10b981;color:white;padding:8px 14px;border-radius:6px;text-decoration:none;font-size:13px;font-weight:600;white-space:nowrap;">Try Free →</a>
            </div>
            """

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f1f5f9;margin:0;padding:20px;">
<div style="max-width:600px;margin:0 auto;">

  <!-- Header -->
  <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:12px 12px 0 0;padding:32px;text-align:center;">
    <h1 style="color:white;margin:0;font-size:24px;">🤖 {config.SITE_NAME}</h1>
    <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:14px;">Week {week_num} · {datetime.now().strftime('%B %d, %Y')}</p>
  </div>

  <!-- Body -->
  <div style="background:white;padding:32px;border-radius:0 0 12px 12px;">

    <h2 style="color:#1e293b;font-size:20px;margin-top:0;">This Week's Top AI Tool Guides</h2>
    {article_blocks}

    <h2 style="color:#1e293b;font-size:20px;margin-top:28px;">🔥 Top Deals This Week</h2>
    <p style="color:#64748b;font-size:14px;margin-top:-8px;">These are the AI tools I personally recommend right now:</p>
    {deals_blocks}

    <div style="background:#fefce8;border:1px solid #fde047;border-radius:8px;padding:16px;margin:24px 0;">
      <p style="color:#713f12;margin:0;font-size:14px;">
        💡 <strong>Tip of the week:</strong> If you're only going to try one AI tool this month, make it
        <a href="{AFFILIATE_PROGRAMS['jasper']['signup_url']}" style="color:#6366f1;">Jasper AI</a>.
        It's the most complete writing assistant available, and their free trial is genuinely impressive.
      </p>
    </div>

    <p style="color:#94a3b8;font-size:13px;margin-top:24px;">
      — The {config.SITE_NAME} Team<br>
      <a href="{config.SITE_URL}" style="color:#6366f1;">{config.SITE_URL}</a>
    </p>
  </div>

  <!-- Footer -->
  <div style="text-align:center;padding:16px;">
    <p style="color:#94a3b8;font-size:12px;margin:4px 0;">
      You're receiving this because you subscribed at {config.SITE_URL}<br>
      <a href="{config.SITE_URL}/unsubscribe" style="color:#6366f1;">Unsubscribe</a>
    </p>
  </div>
</div>
</body>
</html>"""

def send_weekly_newsletter():
    """Send weekly newsletter to all active subscribers. Called every Monday by scheduler."""
    articles = get_articles(limit=5)
    if not articles:
        log.warning("No articles to feature in newsletter")
        return 0

    week_num = datetime.now().isocalendar()[1]
    html = generate_newsletter_html(articles, week_num)
    subscribers = get_subscribers(status='active')

    if not subscribers:
        log.info("No subscribers yet")
        return 0

    emails = [s["email"] for s in subscribers]
    subject = f"[Week {week_num}] {articles[0]['title']} + more AI tool news"

    sent = 0
    # Resend batch (max 50 at a time to respect rate limits)
    for i in range(0, len(emails), 50):
        batch = emails[i:i+50]
        try:
            resend.Emails.send({
                "from": f"{config.FROM_NAME} <{config.FROM_EMAIL}>",
                "to": batch,
                "subject": subject,
                "html": html,
            })
            sent += len(batch)
            log.info(f"Newsletter batch sent: {len(batch)} emails")
        except Exception as e:
            log.error(f"Newsletter batch failed: {e}")

    log.info(f"Newsletter sent to {sent} subscribers")
    return sent
